<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Company>Sentja Group</Company>
    <Product>Sentja Cloud</Product>
    <Description>Sentja Cloud Desktop Client</Description>
    <Copyright>Copyright © 2026 Sentja Group</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Clowd.Squirrel" Version="2.11.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SentjaShared\SentjaShared.csproj" />
    <ProjectReference Include="..\SentjaMigration\SentjaMigration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
